kind = "mobile"
previewPath = "/"
title = "Shams Tex"
version = "1.0.0"
id = "artifacts/shamstex"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22659

[services.development]
run = "pnpm --filter @workspace/shamstex run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/shamstex", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/shamstex", "run", "serve" ]

[services.env]
PORT = "22659"
BASE_PATH = "/"
