import React from "react";
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Award,
  Banknote,
  Bell,
  BellOff,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  CheckSquare,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  CreditCard,
  DollarSign,
  Download,
  Droplet,
  ExternalLink,
  Eye,
  FileText,
  Film,
  Gift,
  Globe,
  GripVertical,
  Headphones,
  House,
  Image,
  Inbox,
  Info,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Lock,
  Maximize2,
  MessageCircle,
  Minus,
  Moon,
  Music2,
  Package,
  Pencil,
  PenLine,
  Phone,
  PhoneCall,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Square,
  Star,
  Sun,
  Trash2,
  User,
  UserPlus,
  Users,
  Wallet,
  X,
  XCircle,
  Zap,
  ZapOff,
  AtSign,
  Circle,
  Ghost,
  Map,
  MapPin,
  Play,
  Send,
  Store,
  ThumbsUp,
  Truck,
  Video,
} from "lucide-react-native";

const iconMap: Record<string, React.ComponentType<any>> = {
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  award: Award,
  banknote: Banknote,
  bell: Bell,
  "bell-off": BellOff,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock,
  copy: Copy,
  "credit-card": CreditCard,
  "dollar-sign": DollarSign,
  download: Download,
  droplet: Droplet,
  "edit-2": Pencil,
  "edit-3": PenLine,
  "external-link": ExternalLink,
  eye: Eye,
  facebook: ThumbsUp,
  film: Film,
  gift: Gift,
  "grip-vertical": GripVertical,
  grid: LayoutGrid,
  headphones: Headphones,
  home: House,
  image: Image,
  inbox: Inbox,
  info: Info,
  instagram: Camera,
  layers: Layers,
  layout: LayoutTemplate,
  lock: Lock,
  "maximize-2": Maximize2,
  "message-circle": MessageCircle,
  minus: Minus,
  moon: Moon,
  package: Package,
  phone: Phone,
  "phone-call": PhoneCall,
  plus: Plus,
  "refresh-cw": RefreshCw,
  "rotate-ccw": RotateCcw,
  "file-text": FileText,
  search: Search,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  square: Square,
  star: Star,
  sun: Sun,
  tiktok: Music2,
  "trash-2": Trash2,
  user: User,
  "user-plus": UserPlus,
  users: Users,
  wallet: Wallet,
  x: X,
  "x-circle": XCircle,
  zap: Zap,
  "zap-off": ZapOff,
  "at-sign": AtSign,
  circle: Circle,
  ghost: Ghost,
  map: Map,
  "map-pin": MapPin,
  play: Play,
  send: Send,
  store: Store,
  "thumbs-up": ThumbsUp,
  truck: Truck,
  video: Video,
  snapchat: Ghost,
  telegram: Send,
  youtube: Play,
  twitter: AtSign,
  linkedin: Briefcase,
  website: Globe,
  globe: Globe,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: any;
}

export default function Icon({ name, size = 24, color = "#fff", style }: IconProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} color={color} style={style} />;
}
