import React from "react";
import {
  AlertCircle,
  ArrowLeft,
  ArrowRight,
  Award,
  Bell,
  BellOff,
  Briefcase,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  DollarSign,
  Droplet,
  ExternalLink,
  Eye,
  Film,
  Globe,
  Headphones,
  House,
  Image,
  Info,
  Layers,
  LayoutGrid,
  LayoutTemplate,
  Lock,
  MessageCircle,
  Minus,
  Moon,
  Music2,
  Package,
  Pencil,
  PenLine,
  Phone,
  PhoneCall,
  Plus,
  Search,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Star,
  Sun,
  Trash2,
  User,
  Users,
  X,
} from "lucide-react-native";

const iconMap: Record<string, React.ComponentType<any>> = {
  "alert-circle": AlertCircle,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  award: Award,
  bell: Bell,
  "bell-off": BellOff,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  check: Check,
  "check-circle": CheckCircle,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  clock: Clock,
  "dollar-sign": DollarSign,
  droplet: Droplet,
  "edit-2": Pencil,
  "edit-3": PenLine,
  "external-link": ExternalLink,
  eye: Eye,
  facebook: Globe,
  film: Film,
  grid: LayoutGrid,
  headphones: Headphones,
  home: House,
  image: Image,
  info: Info,
  instagram: Globe,
  layers: Layers,
  layout: LayoutTemplate,
  lock: Lock,
  "message-circle": MessageCircle,
  minus: Minus,
  moon: Moon,
  package: Package,
  phone: Phone,
  "phone-call": PhoneCall,
  plus: Plus,
  search: Search,
  settings: Settings,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  star: Star,
  sun: Sun,
  tiktok: Music2,
  "trash-2": Trash2,
  user: User,
  users: Users,
  x: X,
};

interface IconProps {
  name: string;
  size?: number;
  color?: string;
  style?: any;
}

export default function Icon({ name, size = 24, color = "#fff", style }: IconProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return <LucideIcon size={size} color={color} style={style} />;
}
