// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fabric-3d-viewer/RealisticView.tsx": () => import("../components/mockups/fabric-3d-viewer/RealisticView.tsx")
};
